// <auto-generated />
using System;
using ImasClipManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImasClipManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202125424_AddClipName")]
    partial class AddClipName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ClipPerformer", b =>
                {
                    b.Property<int>("ClipsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClipsId", "PerformersId");

                    b.HasIndex("PerformersId");

                    b.ToTable("ClipPerformer");
                });

            modelBuilder.Entity("ClipPlaylist", b =>
                {
                    b.Property<int>("ClipsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClipsId", "PlaylistsId");

                    b.HasIndex("PlaylistsId");

                    b.ToTable("ClipPlaylist");
                });

            modelBuilder.Entity("ImasClipManager.Models.Clip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Brands")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClipName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConcertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcertName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoThumbnail")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiveType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SongTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpaceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("Clips");
                });

            modelBuilder.Entity("ImasClipManager.Models.DisplayState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Context")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DisplayStates");
                });

            modelBuilder.Entity("ImasClipManager.Models.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Brand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiveType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Yomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("ImasClipManager.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("ImasClipManager.Models.Space", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("ClipPerformer", b =>
                {
                    b.HasOne("ImasClipManager.Models.Clip", null)
                        .WithMany()
                        .HasForeignKey("ClipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImasClipManager.Models.Performer", null)
                        .WithMany()
                        .HasForeignKey("PerformersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClipPlaylist", b =>
                {
                    b.HasOne("ImasClipManager.Models.Clip", null)
                        .WithMany()
                        .HasForeignKey("ClipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImasClipManager.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImasClipManager.Models.Clip", b =>
                {
                    b.HasOne("ImasClipManager.Models.Space", null)
                        .WithMany("Clips")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImasClipManager.Models.Playlist", b =>
                {
                    b.HasOne("ImasClipManager.Models.Space", "Space")
                        .WithMany("Playlists")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Space");
                });

            modelBuilder.Entity("ImasClipManager.Models.Space", b =>
                {
                    b.Navigation("Clips");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
